name: tasky
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.1
  google_fonts: ^6.2.1
  country_code_picker: ^3.0.0
  fui_kit: ^2.0.2
  image_picker: ^1.1.2
  hugeicons: ^0.0.7
  http: ^1.2.2
  equatable: ^2.0.5
  dotted_border: ^2.1.0
  http_parser: ^4.0.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Image/
    - assets/Translation/
